name: Trunk.io Playwright Reporter CI

on:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.idea/**'
      - 'README.md'
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.idea/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  integration-testing:
    name: Integration testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install && bun link
      - run: cd test/target && bun install && npx playwright install-deps
      - run: bun run-target-tests || true
      - run: cd ../../
      - run: bun run integration
