name: Trunk.io Playwright Reporter CI

on:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.idea/**'
      - 'README.md'
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.idea/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun link
      - run: cd test/target && bun install
      - run: bun run run-target-tests
      - run: bun run integration
