name: Publish package to npmjs

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.idea/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: bun install --frozen-lockfile
      - run: bun publish --dry-run
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
